#!/bin/sh
# Arch Netboot: Netboots Arch Linux with kexec

LINUX="http://mirror.rackspace.com/archlinux/iso/latest/arch/boot/x86_64/vmlinuz-linux"
INITRD="http://mirror.rackspace.com/archlinux/iso/latest/arch/boot/x86_64/initramfs-linux.img"

echo "[-] Starting Arch Linux, please wait."
echo "[-] Obtaining kernel"
wget -O kernel $LINUX
echo "[-] Obtaining initrd"
wget -O initrd.gz $INITRD
echo "[-] Loading the kernel and Image to ram"
kexec -d -l --append="net.ifnames=0 verify=y archiso_http_srv=http://mirror.rackspace.com/archlinux/iso/latest/ archisobasedir=arch ip=dhcp" --initrd=initrd.gz kernel
echo "[-] Off we go!"
kexec -d -e