#!/bin/sh
echo "Shutting down MiniRES on $(date)"
echo "Disconnecting from the internet."
ip link eth0 down || true
ip link wlan0 down || true
echo "Stopping services"
echo "Stopping service gpm (Mouse support)"
killall gpm || echo "Failed."; true
echo "Stopping service udhcpc (DHCP Client)"
killall udhcpc || echo "Failed."; true
echo "Stopping services iwd (WiFi Daemon)"
killall iwd || echo "Failed."; true
echo "Stopping service sshd (SSH Server)"
killall sshd || echo "Failed."; true
#swapoff /dev/zram0
#echo 1 > /sys/block/zram0/reset
#modprobe -r zram
