#!/bin/sh
echo "Starting"
mount -t sysfs sys /sys
mount -t proc proc /proc
mount -t devtmpfs dev /dev
#modprobe zram
#busybox free | busybox grep Mem | busybox awk {'print $2*2'} > /sys/block/zram0/disksize
#busybox mkswap /dev/zram0
#busybox swapon /dev/zram0 -p 10
find /sys -name modalias -type f -print0 | xargs -0 sort -u | xargs modprobe -b -a 2> /dev/null
find /sys -name modalias -type f -print0 | xargs -0 sort -u | xargs modprobe -b -a 2> /dev/null
modprobe mousedev || true
if [ -e /dev/fb0 ] && ! [ -e /sys/module/fbcon ]; then
                modprobe -b -q fbcon
fi
/usr/bin/dbus-daemon &> /tmp/dbus.log &
/usr/libexec/iwd &> /tmp/iwd.log &
hostname "minires-${RANDOM}"
ip link set eth0 up && dhcpcd eth0 || echo "No ethernets?"
gpm -m /dev/psaux -t ps2 &
clear
cat /etc/motd