name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    if: ${{ github.actor != 'github-actions' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: sudo apt update; sudo apt install -y libelf-dev bison bc flex gcc
      # Runs a single command using the runners shell
      - name: Build
        run: sudo bash build_all.sh

      - name: Push updated config file
        run: cp kernel/src/out/.config kernel/kconfig
      
      - name: Update kernel config
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            kernel/kconfig
          commit-msg: Update kernel config
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: upload kernel
  
        uses: actions/upload-artifact@v3.0.0
        with:
            name: kernel
            path: kernel/bzImage
            if-no-files-found: error
              
      - name: upload initrd
  
        uses: actions/upload-artifact@v3.0.0
        with:
            name: initrd
            path: out.cpio.gz
            if-no-files-found: error
      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
